version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.18.0
    steps:
      - checkout
      - run: 
          name: NPM Install
          command: npm install
      - run: 
          name: Build ’Em All
          command: npm run build
workflows:
  test_build:
    jobs:
      - build
