import {
  DEBUG_NAMESPACE,
  delegateEIP721Types,
  DelegateSignerMessage,
  eip721Domain,
  getAuthEIP721Types,
  SignatureType,
  SilentDataRollupBase,
} from '@appliedblockchain/silentdatarollup-core'
import debug from 'debug'
import { hashMessage, JsonRpcPayload } from 'ethers'
import {
  PeerType,
  TransactionArguments,
  TransactionOperation,
} from 'fireblocks-sdk'

const log = debug(DEBUG_NAMESPACE)

export class SilentDataRollupFireblocksBase extends SilentDataRollupBase {
  public async createPersonalSignature(
    provider: any,
    content: any,
    operation: TransactionOperation,
    type?: SignatureType
  ): Promise<string> {
    log('Signing message. Operation:', {
      operation,
      type,
      content,
    })
    const vaultAccountId = provider.ethereum.vaultAccountIds[0]?.toString()
    log('Using vault account ID:', vaultAccountId)
    const transactionArguments: TransactionArguments = {
      operation,
      assetId: provider.ethereum.assetId,
      source: {
        type: PeerType.VAULT_ACCOUNT,
        id: vaultAccountId,
      },
      extraParameters: {
        rawMessageData: {
          messages: [
            { content, ...(type === SignatureType.EIP712 ? { type } : {}) },
          ],
        },
      },
    }

    log('Creating transaction', JSON.stringify(transactionArguments, null, 2))
    const txInfo = await provider.ethereum.createTransaction(
      transactionArguments
    )
    log('Transaction created. TxInfo:', txInfo)
    const sig = txInfo!.signedMessages![0].signature
    const v = 27 + sig.v!
    const signature = '0x' + sig.r + sig.s + v.toString(16)
    log('Signature generated:', signature)
    return signature
  }

  public async signRawDelegateHeader(
    provider: any,
    message: DelegateSignerMessage
  ): Promise<string> {
    const stringifiedMessage = JSON.stringify(message)
    log('Signing raw delegate header. Message:', stringifiedMessage)
    const hashedMessage = hashMessage(stringifiedMessage).slice(2)
    return this.createPersonalSignature(
      provider,
      hashedMessage,
      TransactionOperation.RAW,
      SignatureType.Raw
    )
  }

  public async signTypedDelegateHeader(
    provider: any,
    message: DelegateSignerMessage
  ) {
    log('Signing typed delegate header. Message:', message)

    const content = {
      types: {
        EIP712Domain: [
          { name: 'name', type: 'string' },
          { name: 'version', type: 'string' },
        ],
        ...delegateEIP721Types,
      },
      primaryType: 'Ticket',
      domain: eip721Domain,
      message: message,
    }

    log('EIP712 content created:', content)
    return this.createPersonalSignature(
      provider,
      content,
      TransactionOperation.TYPED_MESSAGE,
      SignatureType.EIP712
    )
  }

  public async signAuthHeaderRawMessage(
    provider: any,
    payload: JsonRpcPayload | JsonRpcPayload[],
    timestamp: string
  ): Promise<string> {
    log('Preparing raw message for signing')
    const message = this.prepareSignatureMessage(payload, timestamp)
    log('Raw message:', message)
    let signature: string
    if (this.config.delegate) {
      const delegateSigner = await this.getDelegateSigner(this)
      signature = await this.signMessage(delegateSigner, message)
      log('Raw signature generated by delegate signer:', signature)
    } else {
      log('Message to be hashed:', JSON.stringify(message))
      const hashedMessage = hashMessage(message).slice(2)
      log('Hashed message:', hashedMessage)

      signature = await this.createPersonalSignature(
        provider,
        hashedMessage,
        TransactionOperation.RAW
      )
    }

    log('Raw signature generated:', signature)
    return signature
  }

  public async signAuthHeaderTypedData(
    provider: any,
    payload: JsonRpcPayload | JsonRpcPayload[],
    timestamp: string
  ): Promise<string> {
    const types = getAuthEIP721Types(payload)
    const message = this.prepareSignatureTypedData(payload, timestamp)

    const content = {
      types: {
        EIP712Domain: [
          { name: 'name', type: 'string' },
          { name: 'version', type: 'string' },
        ],
        ...types,
      },
      primaryType: 'Call',
      domain: eip721Domain,
      message: message,
    }

    log('EIP712 content created:', content)
    let signature: string
    if (this.config.delegate) {
      const delegateSigner = await this.getDelegateSigner(this)
      signature = await delegateSigner!.signTypedData(
        eip721Domain,
        types,
        message
      )
    } else {
      signature = await this.createPersonalSignature(
        provider,
        content,
        TransactionOperation.TYPED_MESSAGE,
        SignatureType.EIP712
      )
    }

    log('Typed signature generated:', signature)
    return signature
  }
}
